name: Build, Test, and Release

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: [ 3.12 ]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller

            - name: Install GitHub CLI
              run: sudo apt-get install gh

            - name: Authenticate GitHub CLI
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: echo "${{ secrets.GH_TOKEN }}" | gh auth login --with-token

            - name: Run tests
              run: |
                  pip install -r requirements.txt
                  python -m unittest discover -s tests

            - name: Build executable
              run: |
                  pyinstaller --onefile src/ghw.py --name ghw

            - name: Archive binary
              uses: actions/upload-artifact@v2
              with:
                  name: ghw
                  path: dist/ghw

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download binary
              uses: actions/download-artifact@v2
              with:
                  name: ghw
                  path: .

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  draft: false
                  prerelease: false
                  token: ${{ secrets.GH_TOKEN }}

            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./dist/ghw
                  asset_name: ghw
                  asset_content_type: application/octet-stream
